version: '3.8'
services:
  fe:
    build: ./dockerfiles/fe
    environment:
     - ENV=local
    ports:
      - '3000:80'
    volumes: 
      - fe:/graficobollette/fe/node_modules
    depends_on:
      - be
  be:
    build: ./dockerfiles/be
    environment:
     - ENV=local
     - DB_HOST=jdbc:postgresql://postgres:5432/postgres
     - DB_USER=paoloattili
     - DB_PASSWORD=psqlpsswd
    ports:
      - '8080:8080'
    volumes: 
      - be:/graficobollette/be/logs
    depends_on:
      - db
  db:
    image: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=paoloattili
      - POSTGRES_PASSWORD=psqlpsswd
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  fe:
    driver: local
  be:
    driver: local
  db:
    driver: local
  